[book]
authors = ["Captain Nick Lucifer*"]
language = "en"
multilingual = false
src = "src"
title = "NtH1M Documentation"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/c4p-n1ck/NtH1M"
edit-url-template = "https://github.com/c4p-n1ck/NtH1M-docs/edit/master/src/{path}"

[[output.html.links]]
title = "NtH1M Repository!"
icon = "fa-github"
href = "https://github.com/c4p-n1ck/NtH1M"
